# Site settings
title: A.C.C. Guadalupe Ortiz de Landazuri
author:
  name: AACCGODL
  email: glportizdlandazuri@gmail.com
  descripction: "Yo, como siempre, llena de ilusion en lo que hago ahora y en lo que en cada momento dispongan de mi."
  
  # Build settings
  theme: jekyll-theme-minimal
